Football_app/urls.py
from django.contrib import admin
from django.urls import path
from Football_Players_Ratings.views import strona_zawodnicy, zawodnik, terminarz

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lista_zawodnikow/', strona_zawodnicy),
    path('zawodnik/<int:id>/', zawodnik, name='zawodnik_URL' ),
    path('terminarz/', terminarz),
]

Football_Players_Ratings/models.py
from django.db import models

class ListaDruzyn(models.Model):

    nazwa_druzyny = models.CharField(max_length=64, null=False)

    def __str__(self):

        return "{}".format(self.nazwa_druzyny)


class Zawodnik(models.Model):

    POZYCJA_NA_BOISKU = {
        (0, 'Bramkarz'),
        (1, 'Środkowy obrońca'),
        (2, 'Boczny obrońca'),
        (3, 'Środkowy defensywny pomocnik'),
        (4, 'Środkowy ofensywny pomocnik'),
        (5, 'Boczny pomocnik'),
        (6, 'Wahadłowy'),
        (7, 'Napastnik'),
    }
    Imie = models.CharField(max_length=64, null=True)
    Nazwisko = models.CharField(max_length=64, null=True)
    Druzyna = models.ForeignKey(ListaDruzyn, on_delete=models.CASCADE)
    Wiek = models.PositiveSmallIntegerField(null=False)
    Pozycja_na_boisku = models.PositiveSmallIntegerField(choices=POZYCJA_NA_BOISKU)
    Fotografia = models.ImageField(upload_to="fotografie_zawodnikow", null=True, blank=True)

Football_Players_Ratings/views.py
from django.shortcuts import render, get_object_or_404

from .models import Zawodnik, ListaDruzyn

def strona_zawodnicy(request):

    lista_zawodnikow = Zawodnik.objects.all()
    return render(request, 'lista_zawodnikow.html', {'zawodnicy': lista_zawodnikow})

def zawodnik(request, id):

    zawodnik_ = get_object_or_404(Zawodnik, pk=id)
    return  render(request, 'zawodnik.html', {'zawodnik': zawodnik_})

def terminarz(request):

    tempo_bialka = ListaDruzyn.objects.get(id=1)
    halniak_makow = ListaDruzyn.objects.get(id=2)
    garbarz_zembrzyce = ListaDruzyn.objects.get(id=3)
    sucha_beskidzka = ListaDruzyn.objects.get(id=4)
    return render(request, 'terminarz.html', {'tb': tempo_bialka, 'hmp': halniak_makow, 'gz': garbarz_zembrzyce,
                                              'sb': sucha_beskidzka})

Football_Players_Ratings/templates/glowny.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/1eb9cf2c85.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'glowny.css' %}">
    <title>{% block tytul %} {% endblock %}</title>
</head>
<body>
    {% block strona %} {% endblock %}
</body>
</html>

Football_Players_Ratings/templates/lista_zawodnikow.html
{% extends 'glowny.html' %}

{% block tytul %} Lista zawodnikoów {% endblock %}
{% load bootstrap %}

{% block strona %}

    {% for zawodnik in zawodnicy %}


        <a href="{% url 'zawodnik_URL' zawodnik.id %}"> <button type="submit"><h5>
            {{ zawodnik.Imie}} {{ zawodnik.Nazwisko}} ({{ zawodnik.Druzyna }}) </h5></button>  </a> <br>

    {% endfor %}

{% endblock %}

Football_Players_Ratings/templates/terminarz.html
{% extends 'glowny.html' %}

{% block tytul %} Terminarz meczów {% endblock %}
{% load bootstrap %}

{% block strona %}

    <h5> Kolejka 1: X/03/2020 </h5>
    <h6> {{ tb }} - {{ hmp }} </h6>
    <h6> {{ gz }} - {{ sb }} </h6>

{% endblock %}

Football_Players_Ratings/templates/zawodnik.html
{% extends 'glowny.html' %}
{% load bootstrap %}

{% block tytul %} {{ zawodnik.Imie }} {{ zawodnik.Nazwisko }} {% endblock %}


{% block strona %}

    <div class="card" style="width: 30rem;">
          <div class="card-body">

              <div class="row">
                  <div class="col-9">
                    <h5 class="card-title">{{ zawodnik.Imie }} {{ zawodnik.Nazwisko }}</h5>
                  </div>
                  <div class="col-3">
                     Wiek: {{ zawodnik.Wiek }}
                  </div>
              </div>
              <div class="row">
                  <div class="col">
                    <p class="card-text">Pozycja na boisku: {{ zawodnik.get_Pozycja_na_boisku_display }}</p>
                  </div>

              </div>
          </div>
    </div>

{% endblock %}